### ISSUE TITLE
[FEATURE] README 작성

### ISSUE THREAD

**Issue by ohcmadah** [ohcmadah/pre-onboarding-10th-2-9#11]
### 🤸 Describe the required feature

README에 구현 내용 및 특이 사항, 사용법 등 기술

### 🏊 Todo

- [x] 캐싱을 어떻게 기술했는지에 대한 내용
- [x] API 호출 횟수를 줄이는 전략
- [x] 키보드만으로 추천 검색어들로 이동 사용법

### 💬 Additional information

- 이슈, PR 링크가 도움이 된다면 걸기
- 여러 선택지가 있었다면 고민한 내용
