### ISSUE TITLE
[FEATURE] 키보드 조작 구현

### ISSUE THREAD

**Issue by ohcmadah** [ohcmadah/pre-onboarding-10th-2-9#9]
### 🤸 Describe the required feature

키보드만을 이용해 추천 검색어들로 이동할 수 있도록 기능 구현.

### 🏊 Todo

- [x] keyboard 관련 util 추가
- [x] handler 처리
- [x] activeIndex 공유할 수 있도록 Context API 추가
- [x] css 추가
- [x] `App.tsx` 코드 정리
  - 삼항연산자 등 조건문이 많아 더 추상화 하고싶다.

### 💬 Additional information
